Add option to define complete output path
christian-reichart/svg-chameleon pull request #21
Opened 2021-01-31 20:45 UTC by harterSe

Suggestion for #7

2021-02-05 16:27 UTC, christian-reichart requested changes
hey @harterSe  thanks for taking this issue. Left you comments, we still need to do the scss and css dest stuff ;)

2021-02-05 16:27 UTC, christian-reichart commented on src/index.ts
> +    console.log(result)
remove console.log

2021-02-05 16:27 UTC, christian-reichart commented on src/index.ts
> +  console.log(filePath);
remove console.log

2021-02-05 16:27 UTC, christian-reichart commented on README.md
>    css: true,                                // default: false (creates css with classes for dimensions)
@harterSe dest on main object looks good, but the restructuring of the scss and css options is still todo! See my comment on the issue:

```
dimensionStyles: {
    css: {
      create: false, // automatically true if other option is set
      dest: null, // default same dir as sprite
      name: null // default is name
    },
    scss: {
      create: false, // automatically true if other option is set
      dest: null, // default same dir as sprite
      name: null // default is name
    },
  },
```
to keep the cli options simple i would leave --scss and --css to set dimensionStyles.scss/css.create  and expand it with --scss-dest, --scss-name, --css-dest, --css-name

2021-02-05 16:39 UTC, christian-reichart commented on src/index.ts
> +    console.log(result)
Ah, I see you left a todo for me, sorry. What do you mean, has no effect? The result contains information for svg-sprite on which modes were set active in the options (currently we only use symbol mode). https://www.npmjs.com/package/svg-sprite#usage-pattern

2021-02-05 16:44 UTC, christian-reichart commented on src/index.ts
> +    console.log(result)
Ah I see, this comment isn't from you... just delete it with the console.log all together :D I think this was a leftover from the typings merge

2021-02-11 23:19 UTC, christian-reichart requested changes
@harterSe  looks good to me! If you remove the two console logs i can merge this :)

2021-02-11 23:19 UTC, christian-reichart commented on src/index.ts
> +  console.log(customOptions.dimensionStyles)
remove console.log

2021-02-11 23:19 UTC, christian-reichart commented on src/index.ts
> +  console.log(options)
remove console.log

2021-02-12 06:17 UTC, harterSe commented on src/index.ts
> +  console.log(customOptions.dimensionStyles)
Ok I will remove the logs this evening.

2021-02-13 15:46 UTC, harterSe commented on src/index.ts
> +  console.log(customOptions.dimensionStyles)
done

2021-02-13 15:46 UTC, harterSe commented on src/index.ts
> +  console.log(options)
done

2021-02-28 21:05 UTC, merged

2021-02-28 21:06 UTC, christian-reichart commented
@harterSe thanks for your contribution!